font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Bold
bold_font        family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-SemiBold
italic_font      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Italic
bold_italic_font family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-SemiBoldItalic
font_size 10.0
background_opacity 0.89
shell_integration no-cursor
cursor_shape block
#window_padding_width 10

# maps
map ctrl+shift+up change_font_size all +5
map ctrl+shift+down change_font_size all -5
map ctrl+up change_font_size all +2.0
map ctrl+down change_font_size all -2.0
map ctrl+0 change_font_size all 0

# bell
enable_audio_bell no

# no warning
confirm_os_window_close 0

# tab bar
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_min_tabs 1

# BEGIN_KITTY_THEME
# One Dark
include onedark.conf
# END_KITTY_THEME
