source = $HOME/.config/hypr/conf/bindings.conf
source = $HOME/.config/hypr/conf/variables.conf
source = $HOME/.config/hypr/conf/apps.conf
source = $HOME/.config/hypr/conf/environment.conf
source = $HOME/.config/hypr/conf/windowrules.conf
