# programs
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#exec='/home/greatbot/.config/scripts/initial-setup.sh > /home/greatbot/.config/scripts/setup.log 2&>1'
exec-once=hyprpaper
exec-once=pipewire
exec-once=wireplumber
exec-once=pipewire-pulse 
exec-once=wl-gammarelay-rs
#exec-once=/home/greatbot/.config/scripts/code_from_reddit/socket_code/socket_logger_starter.shadow
