# windowrules
##windowrulev2 = opacity 0.85, class:^(code-oss)$

windowrulev2 = opacity 0.95, class:^(org.telegram.desktop)$
windowrulev2 = float, class:^(org.telegram.desktop)$
windowrulev2 = size 1209 911, class:^(org.telegram.desktop)$
windowrulev2 = move 342 85, class:^(org.telegram.desktop)$

#windowrulev2 = opacity 0.95, class:^(firefox)$
windowrulev2 = float, class:^(firefox)$, title:^(Picture-in-Picture)
windowrulev2 = size 914 514, class:^(firefox)$, title:^(Picture-in-Picture)  # non funzionano lol

windowrulev2 = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = size 783 516, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = move 1121 17, class:^(org.pulseaudio.pavucontrol)$

windowrulev2 = fullscreen, class:^(feh)$

windowrulev2 = workspace 5, class:^(com.obsproject.Studio)$

#windowrulev2 = opacity 0.95, class:^(MuPDF)$
