#!/usr/bin/env bash

HYPERCTL_PATH=$(which hyprctl)

$HYPERCTL_PATH monitors | grep 0x0003F3ED 1> /dev/null;
HYPERCTL_EXIT_CODE=$?;

hyprpRestarter(){
    PID=$(ps -ef | awk '$8=="hyprpaper" {print $2}');
    AWK_EXIT_CODE=$?;
    
#    if [ AWK_EXIT_CODE -eq 0 ]; then
        kill -9 ${PID};
        hyprpaper > /dev/null 2>&1 &
#    fi
}

if [ $HYPERCTL_EXIT_CODE -eq 0 ]; then
    $HYPERCTL_PATH --batch "keyword monitor eDP-1,disable ; keyword monitor HDMI-A-1,2560x1080@60,0x0,1";
    sed -zi 's/default.png/default_uw.png/2' /home/greatbot/.config/hypr/hyprpaper.conf;
    hyprpRestarter
else
    $HYPERCTL_PATH keyword monitor eDP-1,1920x1200@60,0x0,1;
    sed -zi 's/default_uw.png/default.png/2' /home/greatbot/.config/hypr/hyprpaper.conf;
    hyprpRestarter
fi
